---
apiVersion: v1
kind: Namespace
metadata:
  name: zipkin
  labels:
    name: zipkin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zipkin
  template:
    metadata:
      labels:
        name: zipkin
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - xray
            topologyKey: kubernetes.io/hostname
            namespaces:
            - amazon-cloudwatch
      containers:
      - name: zipkin-aws
        image: iamsouravin/zipkin-aws:0.21.2-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: http-in
          containerPort: 9411
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 512Mi
        env:
        - name: MODULE_OPTS
          value: '-Dlogging.level.zipkin2=INFO -Dloader.path=xray -Dspring.profiles.active=xray'
        - name: QUERY_ENABLED
          value: 'false'
        - name: STORAGE_TYPE
          value: xray
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: xray.amazon-cloudwatch:2000
        - name: AWS_XRAY_NAME_REPLACE_ASTERISK_WITH_CHAR
          value: ':'
        livenessProbe:
          tcpSocket:
            port: http-in
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http-in
          initialDelaySeconds: 35
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tracer
  namespace: zipkin
spec:
  selector:
    name: zipkin
  ports:
  - name: tcp-in
    port: 9411
    protocol: TCP